version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.17
    working_directory: ~/pokemon-autochess

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run: yarn prepare
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      
      - persist_to_workspace:
        root: /tmp/workspace
        paths:
          - build
          - node_modules
          - package.json

  deploy:
    docker:
      - image: circleci/node:14.17
    working_directory: ~/pokemon-autochess

    steps:
      - attach_workspace:
        at: /tmp/workspace
      - run: yarn gh-pages -d /tmp/workspace/build

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: add-gh-pages