version: 2
commands:
  # Install latest yarn dependencies
  install_deps:
    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    docker:
      - image: circleci/node:14.17
    working_directory: ~/pokemon-autochess

    steps:
      - checkout
      - install_deps
      - run: yarn prepare
      - run: yarn lint
      - run: yarn test
      - run: yarn build

  deploy:
    requires: build
    filters:
      branches:
        only: master

    docker:
      - image: circleci/node:14.17
    working_directory: ~/pokemon-autochess

    steps:
      - run: yarn deploy
